範囲選択画面のアップデート
Synesthesias/PLATEAU-SDK-for-Unreal pull request #124
Opened 2023-07-19 15:17 UTC by sacchy

## 実装内容

・範囲選択画面で表示されるアイコンの表示順序修正対応をしました

## マージ前確認項目
- [ ] Squash and Mergeが選択されていること
- [ ] UI、挙動に変更ある場合、ユーザーマニュアルが更新されていること

## 動作確認

・範囲選択画面を開いてアイコンが期待通りの並びになっているか確認します

2023-07-21 09:08 UTC, dazzhe commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.cpp
> + */
doxygenコメントheaderに記載お願いします！

2023-07-21 14:28 UTC, dazzhe commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.cpp
> +    return TArray<FString> { "building.png", "plants.png", "props.png", "traffic.png", "underground.png", "bridge.png", "terrain.png", "other.png" };
細かく指定してなかったので恐縮ですが、重要度順にしたいので以下の並びでお願いします！
また、ファイル名複数個所で同じ文字列使用しているので抽象化お願いします。
```suggestion
    return TArray<FString> { "building.png", "traffic.png", "props.png", "bridge.png", "plants.png", "underground.png", "terrain.png", "other.png" };
```

2023-07-21 14:31 UTC, dazzhe requested changes
PRありがとうございます。

いくつかコメントしたので修正後マージお願いします。
また、次回からで大丈夫ですがブランチ名はmainへのfixのみ`hotfix/hoge`で、devへのfixは`fix/hoge`という命名でお願いします。

2023-07-23 05:36 UTC, closed without merging

2023-07-24 02:18 UTC, linoal commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.cpp
> +    return TArray<FString> { "building.png", "plants.png", "props.png", "traffic.png", "underground.png", "bridge.png", "terrain.png", "other.png" };
解決確認しました

2023-07-24 02:19 UTC, linoal commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUFeatureInfoDisplay.cpp
> + */
解決確認しました

2023-07-24 02:22 UTC, linoal commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUAsyncLoadedFeatureInfoPanel.cpp
> +    for (const auto& IconFileName : IconFIleNameList) {
解決確認しました