範囲選択画面のユーザビリティ向上
Synesthesias/PLATEAU-SDK-for-Unreal pull request #72
Opened 2023-04-21 07:23 UTC by rockepan

## 関連リンク

## 実装内容
PLATEAUExtentGizmo.cppファイルのDrawHandle関数内で、
radius変数の設定方法を変更しました。

距離が10000以下　：　変更前のradiusと同じ
距離が10000以上　：　radiusのサイズ固定

## マージ前確認項目

## 動作確認
ミーティングで画面共有した際の動作と同じです。

## その他

2023-05-08 10:03 UTC, dazzhe commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUExtentGizmo.cpp
> +    double radius = FMath::Min(CameraDistance / 20, 500);
https://docs.unrealengine.com/5.1/en-US/epic-cplusplus-coding-standard-for-unreal-engine/
現状則ってない部分も多いですが基本的にUnreal EngineのCoding Standardに従うようにお願いいたします。
```suggestion
    double Radius = FMath::Min(CameraDistance / 20, 500);
```

2023-05-08 10:04 UTC, dazzhe requested changes
PRありがとうございます。
コメントしたので修正お願いいたします。

2023-05-09 10:25 UTC, rockepan commented
いただいたコメントの内容を修正いたしました。
・不要コードの削除
・Unreal Engineコード規約への対応
ご確認お願いします。

2023-05-11 06:29 UTC, dazzhe approved these changes
LGTM 👍

2023-05-11 09:11 UTC, merged