Feature/euw
Synesthesias/PLATEAU-SDK-for-Unreal pull request #74
Opened 2023-04-24 04:47 UTC by sacchy

## 実装内
[e16bcc3a2080c85bbaeb92796a02d96bdceafc02] について
・Slate実装コード内容をBPへ移植
・基本的にUIパーツの切り替えのみの動作

[a7739035776671d6ad44853bd6147f1a060290a5] について
・BPへ移植されたパーツに対しての動作実装
・インポートタブ内のローカルに関しての実装を完了
・ゾーンIDは０から始まっているためコンボボックス選択時に＋１して対応
・ImportSettingsとImportSettingsDetailで同じ様な定義がされているが今回後者は利用していないためImportSettingsに集約
・C++からBPへのintパラメータ受け渡しについてはサポートの関係上static_castで対応
　・例）uint32_t → int64、EPLATEAUMeshGranularity → int

## マージ前確認項目
- [ ] Squash and Mergeが選択されていること
- [ ] UI、挙動に変更ある場合、ユーザーマニュアルが更新されていること

## 動作確認

## その他

2023-04-24 13:36 UTC, dazzhe commented on Source/PLATEAUEditorBPLibraries/Private/PLATEAUImportAreaSelectBtn.cpp
> + * @param bImportFromServer サーバ起動か？
```suggestion
 * @param bImportFromServer サーバからインポートするかどうか
```

2023-04-24 13:44 UTC, dazzhe commented on Source/PLATEAUEditorBPLibraries/Private/PLATEAUImportLocalBtn.cpp
> +    		const auto InDatasetSource = plateau::dataset::DatasetSource::createLocal(TCHAR_TO_UTF8(*OutFolderName));
他の部分含めてタブ置き換えお願いします。
```suggestion
    	    const auto InDatasetSource = plateau::dataset::DatasetSource::createLocal(TCHAR_TO_UTF8(*OutFolderName));
```

2023-04-24 13:56 UTC, dazzhe commented on Source/PLATEAUEditorBPLibraries/Private/PLATEAUImportModelBtn.cpp
> +void UPLATEAUImportModelBtn::LocalImportModel(const int ZoneID, const FString& SourcePath, const FVector& ReferencePoint, const TMap<int64, FPackageInfoSettings> PackageInfoSettingsData) {
参照渡しがベターかと思います。
```suggestion
void UPLATEAUImportModelBtn::LocalImportModel(const int ZoneID, const FString& SourcePath, const FVector& ReferencePoint, const TMap<int64, FPackageInfoSettings>& PackageInfoSettingsData) {
```

2023-04-24 14:02 UTC, dazzhe commented on Source/PLATEAURuntime/Public/PLATEAUImportSettings.h
> +        Items.Add(static_cast<int64>(plateau::dataset::PredefinedCityModelPackage::Building), LOCTEXT("PrimaryFeatureObject", "建築物"));
LOCTEXTの一つ目の引数はキーなのでそれぞれ別の名称設定お願いします。
```suggestion
        Items.Add(static_cast<int64>(plateau::dataset::PredefinedCityModelPackage::Building), LOCTEXT("Building", "建築物"));
```

2023-04-24 14:05 UTC, dazzhe requested changes
PRありがとうございます。
モジュール構成、ファイル構成分かりやすくていいですね！
コメントも多く記載いただき大変助かります。
以下気になる点コメントしてますので修正お願いします。

## 挙動に関して
- [ ] 存在しない設定に空白が出てしまっているため、切り詰めお願いします。(HiddenではなくCollapsed?)
![image](https://user-images.githubusercontent.com/10482465/234010404-81ac51a7-e17c-468e-8d31-de56f6e98b94.png)
- [ ] 範囲選択を開く→完了を押す度に無限にパッケージ項目増えて行くため修正お願いします。
![image](https://user-images.githubusercontent.com/10482465/234010743-c7927d90-5160-426c-a6d8-3bfba331adc2.png)

## 実装に関して
- [ ] UIの不要なpngファイル(dark_gradation_long.png等)削除お願いします。
- [ ] PLATEAUFeatureImportSettingsDetails等恐らく不要になったコードあるかと思いますので削除お願いします。
- [ ] その他気になった点コードにコメントしてます。

2023-04-26 15:53 UTC, sacchy commented on Source/PLATEAUEditorBPLibraries/PLATEAUEditorBPLibraries.Build.cs
> +		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
対応しました！

2023-04-26 15:53 UTC, sacchy commented on Source/PLATEAUEditorBPLibraries/Private/PLATEAUImportAreaSelectBtn.cpp
> + * @param bImportFromServer サーバ起動か？
対応しました！

2023-04-26 15:55 UTC, sacchy commented
> UIの不要なpngファイル(dark_gradation_long.png等)削除お願いします。
> PLATEAUFeatureImportSettingsDetails等恐らく不要になったコードあるかと思いますので削除お願いします。

スレート版のUIや挙動を確認する必要があるため最後に削除します。

2023-05-11 09:10 UTC, sacchy commented
[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/72e187a8de8e2399b15d29ac084759bc640b15a5] について
・インポートパネルのサーバ対応
・ExtentEditor上でPackageMaskをローカルとサーバで分けて保持

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/2caf8981e8c01b2e6d4ad0c0bc12b48fe84b54c4]について
・プルリク指摘対応

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/296848127ad9b597a29a72cd66eef09391883669]について
・エリア選択画面を開いた時にハンドルが画面上に無いことがある問題の対応

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/0268404d284b4ac74be80c02324543de742ed018]について
・Building、Relief、Vegetation、その他に分けて実装（C++、BP共に）
・複数ファイルから呼び出される機能はUtilへ

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/5044553e360676fdd4dc15d328689c3f066b30bd]について
・コピーライト文言修正対応

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/1bdb2949adae48e1e7e1ffb64b7b53c5ad58d236]について
・dev取り込み

[https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/pull/74/commits/2cef0c55a784bfecd33406fbcfb8f79115693efe]について
・コンフリクト対応

[]について
・

2023-05-15 07:42 UTC, sacchy commented
[c28f4d0e4154551d92e4a566511ace540e05a8d2] について
・インポートキャンセル対応
・LoaderのUObjectをBPに渡しキャンセル処理実行

[ddd514ff8c2a1433a218e4e7d274da6fe2775f0f] について
・関数名変更による修正

[04a928b098edd7f4b80d58f26109a305e1851af5]について
・UE5.2との互換性がなくアセットが破損したため修正

2023-05-16 05:47 UTC, dazzhe commented on Source/PLATEAURuntime/Public/PLATEAUImportSettings.h
> +        Items.Add(EPLATEAUMeshGranularity::PerAtomicFeatureObject, LOCTEXT("AtomicFeatureObject", "最小地物単位"));
対応逆になっているので修正お願いします。
```suggestion
        Items.Add(EPLATEAUMeshGranularity::PerPrimaryFeatureObject, LOCTEXT("PrimaryFeatureObject", "最小地物単位"));
        Items.Add(EPLATEAUMeshGranularity::PerAtomicFeatureObject, LOCTEXT("AtomicFeatureObject", "主要地物単位"));
```

2023-05-16 05:48 UTC, dazzhe requested changes
修正ありがとうございます。
一点だけコメントしたので修正後マージお願いします。

2023-05-19 01:55 UTC, dazzhe approved these changes
LGTM :+1:

2023-05-19 02:04 UTC, merged