Unrealでの範囲選択画面に地域メッシュ番号を表示
Synesthesias/PLATEAU-SDK-for-Unreal pull request #81
Opened 2023-05-11 08:51 UTC by rockepan

## 実装内容

■ PLATEAUExtentEditorVPClient.cppの変更内容

　地域メッシュ番号をキャンバスに描画する必要があるため
　「FCanvas」が利用可能なDrawCanvas関数を追加しました。

　DrawCanvas関数内から、実際に地域メッシュ番号を描画する、
　DrawRegionMeshID関数を呼び出す構成になっています。

■ PLATEAUMeshCodeGizmo.cppの変更内容

　FPLATEAUMeshCodeGizmoクラス内で、実際に地域メッシュ番号を
　描画するために、DrawRegionMeshID関数を追加しました。

描画するメッシュ番号の文字列のサイズが固定になる仕様を回避するために、
カメラの距離に応じて、２次メッシュ、３次メッシュの表示を切り替えます。

## 動作確認

範囲選択ウインドウ内で、カメラが一定の距離よりも近い場合に、３次メッシュ（ブルー）の
地域メッシュが表示されます。カメラの距離が遠くなると2次メッシュ（ブラック）の
地域メッシュ番号が表示されます。カメラの距離が一定以上遠くなると、表示領域が
確保できないため、地域メッシュ番号を非表示にします。

> 4000以下　：　３次メッシュの地域メッシュ番号（ブルー）を表示します。
> 4000 - 100000　：　２次メッシュの地域メッシュ番号（ブラック）を表示します。
>            100000以上　：　表示領域が確保できないため、地域メッシュ番号を非表示にします。

2023-05-29 08:14 UTC, rockepan commented
## 実装内容

DrawCanvas関数の引数「FCanvas&」クラス内に、システムのDPI（解像度）を
取得する目的で、GetDPIScale関数が利用できることを確認しました。
この値は、システムのDPI値と連動していて、例えばシステムのDPIが125%の場合、
Canvas.GetDPIScale関数により、フロート値「1.25」が取得できます。
この値を実際の表示位置の補正に利用することでズレの補正を実装しています。

`void FPLATEAUExtentEditorViewportClient::DrawCanvas(FViewport& InViewport, FSceneView& View, FCanvas& Canvas) {`

ちなみに、DPI値を大きな値に設定するに比例して、地域メッシュコードの文字の表示サイズも拡大されます。

2023-05-31 00:41 UTC, rockepan commented
「PLATEAUMeshCodeGizmo.cpp」の「DrawRegionMeshID」関数内の
２次メッシュ、３次メッシュの地域メッシュ番号の表示を切り替える
距離「NearOffset」変数を「4000」から、「8000」に変更。
その他、リファクタリングに対応しました。

2023-05-31 06:35 UTC, dazzhe commented on Source/PLATEAUEditor/Private/ExtentEditor/PLATEAUExtentEditorVPClient.cpp
> +
https://docs.unrealengine.com/4.27/ja/ProgrammingAndScripting/ProgrammingWithCPP/Assertions/
checkマクロでMeshCodesとMeshCodeGizmosのサイズが同じことの検証の追加お願いします。

2023-05-31 06:36 UTC, dazzhe requested changes
PRありがとうございます。
一点コメントしたので修正後マージお願いします。

2023-05-31 08:23 UTC, merged